name: simsppob
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.10
  dartz: ^0.10.1
  dio: ^5.3.2
  encrypt: ^5.0.2
  equatable: ^2.0.5
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.4.1
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  http: ^1.1.0
  internet_connection_checker_plus: ^2.0.0
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/vectors/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Bold.ttf
